import pyautogui as auto
auto.sleep(2)
auto.hotkey('ctrl', 'alt', '6')
auto.sleep(15)
auto.click()
auto.hotkey('ctrl', 'num1')
auto.hotkey('ctrl', 'num2')
auto.hotkey('ctrl', 'num3')
auto.hotkey('ctrl', 'num4')
auto.hotkey('ctrl', 'num5')
auto.hotkey('ctrl', 'e')
auto.sleep(5)
auto.write('n')
auto.press('enter')
auto.sleep(3)
auto.hotkey('ctrl', 't')
auto.sleep(1)
auto.write('u')
auto.press('enter')
auto.sleep(5)
auto.moveTo(x=1299, y=165)
auto.moveTo(x=1185, y=321)
auto.click()
auto.sleep(5)
auto.scroll(-500)
auto.sleep(2)
auto.hotkey('ctrl', 't')
auto.sleep(2)
auto.write('f')
auto.press('enter')
auto.sleep(8)
auto.click(x=700, y=541)
auto.sleep(8)
auto.click(x=720, y=400)
auto.sleep(3)
auto.scroll(-300)
auto.sleep(2)
auto.click(x=252, y=456)
auto.sleep(8)
auto.scroll(-2500)
auto.sleep(2)
auto.click(x=626, y=323)
auto.sleep(2)
auto.scroll(-300)
auto.hotkey('ctrl', 't')
auto.sleep(1)
auto.click(x=1217, y=50)
